In [22]:
import yfinance as yf
import pandas as pd
import numpy as np

In [26]:
# Get data stock data
aapl = yf.download("AAPL", start="2023-1-1", end="2024-1-1", interval="1d")

# Add average candle price
aapl['avg'] = np.min(aapl['Open']) + np.abs(aapl['Open'] - aapl['Close'])/2

# Store average candle prices
avg_prices = np.round(list(aapl['avg']), 2)

aapl

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,avg
Date,,,,,,,
2023-01-03,130.279999,130.899994,124.169998,125.070000,124.048042,112117500,128.615002
2023-01-04,126.889999,128.660004,125.080002,126.360001,125.327507,89113600,126.275002
2023-01-05,127.129997,127.769997,124.760002,125.019997,123.998451,80962700,127.065002
2023-01-06,126.010002,130.289993,124.889999,129.619995,128.560867,87754700,127.814999
2023-01-09,130.470001,133.410004,129.889999,130.149994,129.086533,70790800,126.170006
...,...,...,...,...,...,...,...
2023-12-22,195.179993,195.410004,192.970001,193.600006,193.091385,37122800,126.799995
2023-12-26,193.610001,193.889999,192.830002,193.050003,192.542816,28919300,126.290001
2023-12-27,192.490005,193.500000,191.089996,193.149994,192.642548,48087700,126.339996
2023-12-28,194.139999,194.660004,193.169998,193.580002,193.071426,34049900,126.290001
2023-12-29,193.899994,194.399994,191.729996,192.529999,192.024185,42628800,126.695000

In [27]:
avg_prices

array([128.62, 126.28, 127.07, 127.81, 126.17, 126.25, 127.13, 126.25,
       127.38, 126.57, 126.82, 126.61, 127.31, 127.51, 127.12, 126.5 ,
       126.41, 127.39, 126.99, 126.81, 126.74, 126.97, 129.25, 126.43,
       128.01, 126.99, 127.47, 126.78, 127.46, 126.55, 127.12, 126.11,
       126.11, 126.87, 126.03, 126.36, 126.21, 126.11, 126.19, 126.77,
       126.78, 127.51, 126.03, 127.06, 126.04, 127.5 , 126.87, 127.34,
       126.67, 126.91, 127.86, 126.55, 127.17, 126.99, 126.75, 126.06,
       126.71, 126.84, 126.17, 126.71, 126.43, 127.24, 126.96, 126.5 ,
       126.5 , 127.13, 126.32, 126.79, 126.57, 127.97, 126.32, 126.08,
       126.19, 126.93, 126.29, 126.03, 126.18, 126.72, 126.36, 127.62,
       126.6 , 126.17, 126.79, 127.04, 126.46, 127.31, 126.52, 126.65,
       126.28, 126.06, 126.53, 126.56, 126.05, 126.5 , 127.04, 126.62,
       126.12, 126.8 , 126.39, 126.3 , 127.06, 126.18, 126.05, 127.21,
       126.05, 127.54, 126.39, 126.32, 127.35, 126.28, 127.27, 126.26,
       126.3 , 127.03, 126.92, 126.31, 126.48, 127.64, 126.57, 126.79,
       127.1 , 126.67, 126.26, 127.18, 126.67, 126.13, 127.  , 126.38,
       126.33, 126.55, 126.06, 126.03, 126.24, 127.06, 126.2 , 127.01,
       126.99, 127.09, 126.34, 126.15, 126.43, 127.41, 126.59, 126.21,
       126.33, 127.24, 126.21, 127.78, 127.65, 126.07, 127.35, 126.76,
       126.24, 126.76, 126.73, 126.29, 127.58, 127.11, 126.39, 126.1 ,
       127.31, 128.15, 126.62, 126.06, 128.22, 127.36, 126.03, 126.03,
       126.72, 128.75, 127.2 , 126.1 , 126.37, 127.61, 127.16, 126.88,
       126.75, 126.76, 126.79, 127.89, 126.32, 126.07, 126.95, 127.44,
       127.11, 126.69, 126.42, 127.28, 126.08, 127.3 , 126.57, 127.86,
       127.1 , 126.15, 126.81, 126.33, 127.29, 127.  , 126.26, 126.14,
       126.3 , 127.22, 127.06, 126.21, 126.4 , 127.75, 126.67, 126.64,
       126.72, 127.5 , 127.04, 127.21, 127.43, 127.33, 126.28, 126.29,
       127.22, 126.52, 126.14, 126.09, 126.08, 126.29, 126.79, 126.4 ,
       126.1 , 126.46, 126.08, 126.32, 126.78, 126.07, 126.47, 126.29,
       127.61, 127.07, 126.33, 126.77, 126.04, 126.83, 127.45, 126.06,
       126.03, 126.11, 126.4 , 127.04, 126.72, 126.8 , 126.29, 126.34,
       126.29, 126.69])